name: streamline

packages:
  - .
  - data
  - domain

scripts:
  analyze:
    run: |
      melos exec -- "dart analyze ."
    description: Run Dart analyzer in all packages.

  format:
    run: |
      melos exec -- "dart format ."
    description: Format all Dart files in all packages.

  test:
    run: |
      melos exec -- "dart test"
    description: Run tests in all packages.

  pub_get:
    run: |
      melos exec -- "dart pub get"
    description: Run 'dart pub get' in all packages.

  build_runner_watch:
    run: |
      melos exec -- "dart run build_runner watch --delete-conflicting-outputs"
    description: Run build_runner in watch mode for all packages.