name: streamline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  data:
    path: data
  domain:
    path: domain
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  amicons: ^1.0.1
  flashy_tab_bar2: ^0.0.10
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  
  intl: ^0.20.2
  smooth_page_indicator: ^1.2.1
  shimmer: ^3.0.0
  http: ^1.3.0

  #melos
  melos: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  injectable_generator: ^2.6.2
  riverpod_generator: ^2.6.3
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
