name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  dartz: ^0.10.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.14
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
